#!/bin/bash

set -x

# Add entry to /etc/passwd file.

whoami &> /dev/null || STATUS=$? && true

if [[ "$STATUS" != "0" ]]; then
    cat /etc/passwd | sed -e "s/^default:/builder:/" > /tmp/passwd
    echo "default:x:$(id -u):$(id -g):,,,:/opt/app-root/src:/bin/bash" >> /tmp/passwd
    cat /tmp/passwd > /etc/passwd
    rm /tmp/passwd
fi

# Preserve select environment variables so can set in terminal session.

if [ ! -s /opt/terminal/etc/envvars ]; then
    env | egrep "^PATH=" >> /opt/terminal/etc/envvars
    env | egrep "^LD_LIBRARY_PATH=" >> /opt/terminal/etc/envvars
    env | egrep "^KUBERNETES_" >> /opt/terminal/etc/envvars
    env | egrep "^HOSTNAME=" >> /opt/terminal/etc/envvars
    env | egrep "^JUPYTERHUB_USER=" >> /opt/terminal/etc/envvars
fi

# Setup 'oc' client in advance if configured to be using local OpenShift.

if [ x"$KUBERNETES_PORT_443_TCP_ADDR" != x"" ]; then
    oc config set-cluster local \
            --server "https://$KUBERNETES_PORT_443_TCP_ADDR" \
            --insecure-skip-tls-verify

    oc config set-context local --cluster local
    oc config use-context local

    if [ -f /var/run/secrets/kubernetes.io/serviceaccount/token ]; then
        oc login --token \
            `cat /var/run/secrets/kubernetes.io/serviceaccount/token` \
            --insecure-skip-tls-verify > /dev/null 2>&1
    fi
fi

# Run startup actions if supplied.

if [ -x /opt/app-root/etc/init.d/rc.local ]; then
    /opt/app-root/etc/init.d/rc.local
fi

# Run supervisord.

exec /opt/terminal/bin/supervisord --nodaemon \
    --configuration /opt/terminal/etc/supervisord.conf
