#!/bin/bash

set -x

set -eo pipefail

# Copy files to target directories.

shopt -u dotglob

if [ -d /tmp/src/courses ]; then
    mv /tmp/src/courses/* /opt/app-root/courses/
fi

if [ -d /tmp/src/workspace ]; then
    mv /tmp/src/workspace/* .
fi

rm -rf /tmp/src

# Run custom assemble script if required.

if [ -x ./assemble ]; then
    ./assemble
fi

# Fix up permissions.

fix-permissions /opt/app-root
